### ISSUE TITLE
Have option for map to orient to GPS orientation

### ISSUE THREAD

**Issue by rbanick** [AmericanRedCross/OpenMapKitAndroid#100]
Having an option for the map to orient itself to the same direction as the smartphone/tablet's orientation would improve feature recognition during fieldwork. A lot of our users are not map literate enough to pick out buildings well when the map faces a different direction from where they're facing.

**Comment by hallahan** [comment]
The current mapping lib uses raster tiles, and this would cause labels to be upside down. Also, I specifically turned this off, because it introduced a ton of weird glitches.

We need to wait for MapboxGL/Amigo before considering this feature.

**Comment by hallahan** [comment]
We need a new mapping library to do this. Future phase.
