### ISSUE TITLE
Remove duplicate tag action = 'modify' on created nodes

### ISSUE THREAD

**Issue by imwongela** [AmericanRedCross/OpenMapKitAndroid#101]
OMK adds the tag action = 'modify' twice whenever a user creates a node and tries to save it in odk. This causes an XML parse exception on the ONA osm endpoint. The tag should appear only once for each node. Linked to: https://github.com/onaio/OpenMapKit/issues/23

**Comment by hallahan** [comment]
Fixed bug. Please give it a try by installing this APK:

http://spatialserver.spatialdev.com/omk/apk/OpenMapKit_v0.13.apk

**Comment by d3netxer** [comment]
Do you know @hallahan when this fix will be integrated to the version on the play store? I'm am working on materials for a mapping field project at the end of Jan and I was wondering if I will have to include this step or not.

**Comment by hallahan** [comment]
@dalekunce - can you push the latest release to the Play Store?

https://github.com/AmericanRedCross/OpenMapKitAndroid/releases/tag/v0.14

**Comment by dalekunce** [comment]
0.14 is pushed to the play store. 

cc @hallahan @d3netxer

**Comment by jharpster** [comment]
@d3netxer We're working on updating the docs as well. Would be interested in incorporating more field materials if you're willing to share.

**Comment by d3netxer** [comment]
Ok great @jharpster . As I am working on our field materials, I think I will make edits to the OpenMapKitAndroid Wiki
