### ISSUE TITLE
Adding POI: clicking the '+', then any other icon before confirming crashes OMK?

### ISSUE THREAD

**Issue by PaulUithol** [AmericanRedCross/OpenMapKitAndroid#102]
Found OMK to crash a lot when using POIs, but it seemed to be more of a misunderstanding with the UI/workflow on my part. However, crashing still doesn't seem to be the preferred option. Steps to reproduce:

1. Click the '+' to add a POI
2. Don't confirm the POI addition by clicking `+ add node`; instead, click the 'tags' icon (the 'move' icon will also do the trick, if you're already in 'POI-mode')
3. OMK will crash

**Comment by hallahan** [comment]
Fixed bug. Good catch.
