### ISSUE TITLE
Ability to set a default value for a given tag

### ISSUE THREAD

**Issue by PaulUithol** [AmericanRedCross/OpenMapKitAndroid#104]
__Proposal__: ability to set a default value for a given tag

__Example__: Based on an ODK question, the mapper chooses to map a mobile money agent, and is presented with the requested set of tags for such a POI. In this case, the `amenity` key is already set to the value of `mobile_money`

**Comment by hallahan** [comment]
This issue has been open since March. Please track this via #20
