### ISSUE TITLE
Add ability to input a 'custom' value, in addition the form-specified values

### ISSUE THREAD

**Issue by PaulUithol** [AmericanRedCross/OpenMapKitAndroid#105]
__Proposal__: add the ability to input a 'custom' value for a key, in addition to the set of predefined values in the form

__Example__: for a bank's `operator` key, a number of possible values have been predefined (to minimize errors/typos, and cut down on data entry time), like `Barclays Bank`, `Stanbic Bank`, `Bank of Africa`, and `Finance Trust Bank`. However, these cover only the ones that occur regularly; mappers can encounter other banks, and would need to be able to enter the actual value for the operator for those. So when a mapper find a `Tropical Bank` (yes, it does exist :), he'll need to be able to type this name instead of choosing one of the predefined values.

**Comment by hallahan** [comment]
This is currently being tracked as #58
