### ISSUE TITLE
Duplicate `action` attribute on POI; created OSM file doesn't open in JOSM (parse error)

### ISSUE THREAD

**Issue by PaulUithol** [AmericanRedCross/OpenMapKitAndroid#106]
When trying to open the OSM file generated by a survey (adding a single POI), I get the following message in JOSM:

```
Could not read file 'OSMNode-26030.osm'. Error is: Line 1 column 184: http://www.w3.org/TR/1999/REC-xml-names-19990114#AttributeNotUnique?node&action
```

OpenMapKit generates the following xml in the OSM file for the new POI for me:

```
<?xml version='1.0' encoding='UTF-8' ?><osm version="0.6" generator="OpenMapKit 0.12" user="theoutpost"><node action="modify" id="-1" action="modify" lat="0.3140876690798393" lon="32.57683988999102"><tag k="amenity" v="mobile_money" /><tag k="name" v="A" /><tag k="network" v="MTN" /></node></osm>
```

Removing one of the instances of the `action` attribute fixes this.

**Comment by dalekunce** [comment]
@PaulUithol this is a known bug that is prioritized. #101

**Comment by PaulUithol** [comment]
Ah, sorry, missed that. Feel free to close this one!

**Comment by hallahan** [comment]
I will take on this bug today. Updates to status on #101
