### ISSUE TITLE
changelog 0.13

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/OpenMapKitAndroid#107]
I've seen a 0.13 version APK. We need to have a full list of changes so I can push to the play store.

**Comment by hallahan** [comment]
OK, I can start a changelog. Are you saying that the current APK in the Play Store is 0.13?

Looking at the git tags, the latest is 0.12. Also, the [build.gradle](https://github.com/AmericanRedCross/OpenMapKitAndroid/blob/7ac07668af3fd944aa15ac711084aba93fb3e548/app/build.gradle#L12) file in master was set to 0.12. 

Could you reference where you saw 0.13 in the past?

**Comment by hallahan** [comment]
How about we use Github's release functionality for changelogs. More automatic that way.

https://github.com/AmericanRedCross/OpenMapKitAndroid/releases

https://github.com/AmericanRedCross/OpenMapKitAndroid/releases/new

I'll go ahead and do the next release as 0.14, include the APK this way, and explain what is in the release here. Are you ok with this @dalekunce ?

**Comment by dalekunce** [comment]
sounds good.

**Comment by hallahan** [comment]
Tracking in #90
