### ISSUE TITLE
Automatic created_by tag

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/OpenMapKitAndroid#109]
I see this tag in data from time to time:

https://taginfo.openstreetmap.org/keys/created_by#values

Was there a reason we decided not to do this?

**Comment by mikelmaron** [comment]
It fits better on the changeset tags

**Comment by hallahan** [comment]
Ah cool, I'll think about that when I get to working on submission validation on the Server bit. Thanks!

**Comment by dalekunce** [comment]
I also think that because of the double hop of the data OMK --> JOSM we would lose the grainularity anyway
