### ISSUE TITLE
'random' POI selected when clicking on background map layer

### ISSUE THREAD

**Issue by PaulUithol** [AmericanRedCross/OpenMapKitAndroid#119]
Don't really know how to call this; but what seems to happen:

1. Have a POI layer active (an OSM one in the screenshot). Background layer doesn't seem to matter; both online and mbtiles behave the same
2. Click somewhere on the background
3. A little blue square appear where clicked - with the tagging corresponding to a 'selected' POI somewhere offscreen

I'm putting random in quotes because there does seem to be some logic to it. I can't discover what logic that would be though. It's definitely not the closest one, can be miles away. But it is often the same one 

![screenshot_2016-01-07-10-16-51](https://cloud.githubusercontent.com/assets/670670/12164795/76e3b9f8-b529-11e5-88fc-fd400d608f57.png)
![screenshot_2016-01-07-10-27-45](https://cloud.githubusercontent.com/assets/670670/12164796/76e75e0a-b529-11e5-8c55-d13fe9f32d91.png)

**Comment by hallahan** [comment]
Could you send me a link to the exact OSM dataset you have loaded here? I'd like to reproduce this.

**Comment by PaulUithol** [comment]
Hi Nick, I get this with any dataset we've tried; different base layer, different POI data, even no POI data present at all but a couple of forms/points already surveyed. But for example, try https://drive.google.com/open?id=0Bx3_hrMYdNwLY3VGaXZrOVRwUDQ

**Comment by PaulUithol** [comment]
Occurs with the same data as #121: one form, no osm data, one mbtiles for background.

Form: https://drive.google.com/open?id=0Bx3_hrMYdNwLUV9RZXF6U0pKb1U
Mbtiles: https://drive.google.com/open?id=0Bx3_hrMYdNwLN0taTUJUbXZWdTg

1. Start a new form, just click on the background layer. The blue box will appear.
2. Add one POI ('+', '+ add node'). Immediately add another one ('+', '+ add node')
3. Close the tags window (down arrow next to 'Tags')
4. Click on the background map somewhere. Blue box, one of the POIs will be selected.

With two, which one gets selected still seems somewhat logical. However, that quickly diminishes when you get more (like the screenshot above).

**Comment by PaulUithol** [comment]
@hallahan , any news on this one? It's biting us quite a lot.

**Comment by hallahan** [comment]
I'll take a look. This is a map renderer issue, and we will be replacing the legacy renderer, most likely soon.

This may be a quick fix, however.

**Comment by hallahan** [comment]
Note to self - this would require some sort of buffer around POIs with an intersection check. If this is high priority, pinpoint where that buffer would be put in and figure out LOE (probably higher than we'd like).
