### ISSUE TITLE
Survey Creation Documentation

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/OpenMapKitAndroid#12]
Need a wiki article that shows how to create a survey.

**Comment by mberg** [comment]
We should also put this on xlsform.org

**Comment by dalekunce** [comment]
I think its a great idea. We need to push OMK and an updated ODK to the play store first though.

**Comment by hallahan** [comment]
This will be part of
https://github.com/AmericanRedCross/OpenMapKitWebsite
