### ISSUE TITLE
Multiple select: when retagging, break down value into it's selected options again (if possible)

### ISSUE THREAD

**Issue by PaulUithol** [AmericanRedCross/OpenMapKitAndroid#120]
Probably not quite a bug, just some nicer behavior:

- Select multiple values for a certain key
- Save to ODK
- Redo OSM tagging on the node
- The value will display concatenated at the bottom of the list, instead of having the parts that make up its value selected

It would improve usability if the separate parts were selected; now, it can appear nothing's selected if you have a longer list, since the 'custom' value will be at the bottom, possibly offscreen. One thing to watch out for is what to do if the user did actually type in a custom value instead of sticking to selecting predefined values.

![screenshot_2016-01-08-18-59-42](https://cloud.githubusercontent.com/assets/670670/12217124/ef6ac33c-b707-11e5-9d21-fd156cd379b8.png)

**Comment by hallahan** [comment]
Fixing this should involve a function that splits any given tag value by `;` into corresponding elements, filter out duplicates, and then select the checkboxes with matching values.

I'd really like to understand why there are duplicates at all, however...

**Comment by PaulUithol** [comment]
This also happens when there aren't any duplicates, but simply >1 selected.
