### ISSUE TITLE
display version number in app itself

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/OpenMapKitAndroid#131]
the omk version number should be visible somewhere in the app (either in the top bar or in the settings menu maybe) so you don't have to dig through into the phones settings and installed app menu to check it.

**Comment by hallahan** [comment]
http://stackoverflow.com/questions/4616095/how-to-get-the-build-version-number-of-your-android-application

**Comment by hallahan** [comment]
![2016-04-06 22 16 58](https://cloud.githubusercontent.com/assets/556367/14334663/c12928b8-fc0a-11e5-9a77-0be91f99d89b.png)
