### ISSUE TITLE
Device is Offline

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/OpenMapKitAndroid#142]
Encountered when downloading the deployment before the spring fling.

![img_2382](https://cloud.githubusercontent.com/assets/45/14685020/7bfe2cf6-06e7-11e6-9947-b7195206dad1.JPG)

**Comment by hallahan** [comment]
That's normal. I'd there is no data on the phone or will notify you. Ill improve the error message so that it is more informative.

**Comment by mojodna** [comment]
Ah, I took it to mean that I'd done something wrong, in part because it exposed a path that as a user I probably wouldn't know unless I'd dug around Android before.

**Comment by hallahan** [comment]
I have improved two message to be a little bit more informative.

![screenshot_2016-05-30-11-21-10](https://cloud.githubusercontent.com/assets/556367/15656208/a700cfc6-2659-11e6-8fa8-9524f4979368.png)

![Uploading Screenshot_2016-05-30-11-21-17.png…]()

**Comment by hallahan** [comment]
![screenshot_2016-05-30-11-21-17](https://cloud.githubusercontent.com/assets/556367/15656222/b5298e12-2659-11e6-8f1b-19fc93728eba.png)
