### ISSUE TITLE
Text overlap w/ large tag values

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/OpenMapKitAndroid#143]
![img_2383](https://cloud.githubusercontent.com/assets/45/14685075/cbfcc05a-06e7-11e6-8a58-c798ad0b5211.JPG)

**Comment by hallahan** [comment]
Yeah, I made it prettier just now:

![2016-05-30 19 16 59](https://cloud.githubusercontent.com/assets/556367/15656915/f86e2eb0-2660-11e6-88a9-9de49aba5e49.png)
