### ISSUE TITLE
Enable / Disable Custom Value Input

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/OpenMapKitAndroid#147]
Sometimes we might not want to allow a custom value input for the user.

One example is could be `building`. When this feature was requested, what tags did you have in mind?

cc/ @PaulUithol @dalekunce

**Comment by PaulUithol** [comment]
Any question where there's just a small set of accepted answers; there's
some tags that are only used for yes/no for example. In Uganda, we also had
a list of all possible (regulated) banks for the `operator` key on that
form. `level` could be another one, although restricting that to /[0-9]/
would perhaps be better.

**Comment by hallahan** [comment]
`building:level`? I guess that would make sense in Paris or DC where you know all buildings are below a certain threshold.

Another would be `building:condition`. 

https://wiki.openstreetmap.org/wiki/Key:building:condition

**Comment by dalekunce** [comment]
honestly I think 90% of the time we *do not* want the user to be able to enter a custom value. For me the default should be tags/option only with flag for the potential 'other' value similar to how ODK works now.

**Comment by hallahan** [comment]
Ok, I'll have it off by default.

**Comment by hallahan** [comment]
In the constraints JSON, the custom value input will be enabled if:

```json
"shop": {
    "custom_value": true
  }
```

where `"shop"` is the tag with select one or select multiple  you want to provide the custom value input.
