### ISSUE TITLE
Support for vectors

### ISSUE THREAD

**Issue by y1ds** [AmericanRedCross/OpenMapKitAndroid#153]
It would be nice if it was possible to add vectors in an easy way, either by drawing them on the map or by using a gps track. This could be usefull to map roads, fences, etc

**Comment by dalekunce** [comment]
@y1ds for now this type of feature is not something we are interested in putting development resources into.

**Comment by hallahan** [comment]
We add GeoJSON with Field Papers overlays. Additional vectors will not be appropriate with our current mapping library. If you want more vectors shown, please add it to your OSM XML. That is __support for vectors__, actually.
