### ISSUE TITLE
Zoom to Map Feature on Click

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/OpenMapKitAndroid#18]

**Comment by jharpster** [comment]
Looks like the Amigo renderer will handle this by default.

**Comment by dalekunce** [comment]
@hallahan what is the list of bugs/features we have to have to be able to use MB-GL?

**Comment by hallahan** [comment]
1. Offline Vector Tile rendering pipeline to create up-to-date OSM Mapbox Vector Tiles (major effort).
2. MBTiles Support 
https://github.com/mapbox/mapbox-gl-native/issues/584
3. Spatial Index, Hit Detection, and Selection of Geographic Features 
https://github.com/mapbox/mapbox-gl-native/issues/352

See issue #25

**Comment by hallahan** [comment]
We might want to wait for new map lib for this.

**Comment by hallahan** [comment]
We're going to close this and do this with a new mapping library.
