### ISSUE TITLE
Checkout an area from a QR Code

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/OpenMapKitAndroid#19]
Need the ability to split up an area similar to Field Papers. Users should be able to check out the form, osm file, and mbtiles of the given task area.

**Comment by jj0hns0n** [comment]
We need a map based way to do this too.

**Comment by mberg** [comment]
Loading a overpass query via a QR code into OMK would be another cool
approach to consider

**Comment by jj0hns0n** [comment]
+1 We should be able to bootstrap the entire set of things needed on the device via a map based interface and then get a QR code so others could also do the same.

**Comment by dalekunce** [comment]
@jj0hns0n @mberg you guys are thinking exactly what I am. My original idea was a web page with grid overlay that users can then checkout. Users could leave from a central place or checkout a task through a web interface that downloads the overpass and potentially mbtiles to your phone. This would function similar to how the current HOT tasking manager works.

**Comment by dalekunce** [comment]
After talking with the field paper folks and using it for one day I think this integration needs to be tighter.

**Comment by hallahan** [comment]
Do we still want to do this?

**Comment by dalekunce** [comment]
yes!!!!!

**Comment by hallahan** [comment]
Well then,  let's do it!

**Comment by hallahan** [comment]
One thing we could also do is have OpenMapKit Server generate a QR code for a deployment as well. We don't necessarily need to read a FP QR Code. Deployments are ultimately the responsibility of OpenMapKit Server. 

For now, the goal is FP integration, but it's food for thought on a later phase.

**Comment by dalekunce** [comment]
would be cool as well. FP QR code is just a mini deployment :)

**Comment by hallahan** [comment]
Right now I'm having it automatically download a deployment for a QR code. I'll probably put a button in the map view as well to pan the map to the bounds of the FP scanned with the right MBTiles and OSM activated.

**Comment by hallahan** [comment]
I'm bumping up the LOE a bit. Checking out an area implies that we activate OSM XML and MBTiles layers associated with a Field Papers deployment. For this to make sense, we need to rearrange how files are laid out in the application. 

Right now, they are in `/openmapkit/osm` and `/openmapkit/mbtiles`. Now that we are also downloading `fp.geojson`, it is clear that we really should have files in deployment directories on the phones.

```
/openmapkit/deployments/<name>/
```

This will also lend well to constraints, because custom constraints can be associated with a deployment.

**Comment by hallahan** [comment]
We've got both OSM Layers and Basemap layers working fine with files in deployment directories as well as the original `osm` and `mbtiles` dirs.

Next step is _checking out_ the data on the deployment and showing it on the map.

**Comment by hallahan** [comment]
This is mostly there. I need to have the checkout button show up only when a deployment is done downloading. With that being said, this will close when #122 closes.

**Comment by hallahan** [comment]
This feature is basically there with the deployments. I'm pulling in what I've got to master, should close this issue, at least for how we've described it.
