### ISSUE TITLE
Setup jenkins build server

### ISSUE THREAD

**Issue by jj0hns0n** [AmericanRedCross/OpenMapKitAndroid#22]
We need a continuous integration system to build after every push, run the test suite and produce an apk

Bonus if it can build an apk for specific branches

**Comment by hallahan** [comment]
Sounds great! We should chat to get you up to speed with everything that is going on.

**Comment by hallahan** [comment]
For CI work, note that we set the version of the app in [build.gradle](https://github.com/AmericanRedCross/openmapkit/blob/master/app/build.gradle#L12). We'd want the build to increment this accordingly.

Note that the version of the app is written to saved OSM XML edits like such:

```xml
<?xml version='1.0' encoding='UTF-8' ?><osm version="0.6" generator="OpenMapKit 0.7" user="theoutpost"><node...
```

See commit:
58fbf292cc6cd8558e519b9be87dd9a3faca774a

**Comment by dalekunce** [comment]
How are we doing on this? @jj0hns0n are you going to help get this setup?

**Comment by jj0hns0n** [comment]
Havent made the time to migrate the GeoNode one yet and was going to do
this in parallel. Ill put it on my list for next week and lets plan to have
it done by the 10th.

@nhallahan how much did you look over the other build server I sent. Should
we schedule a time to work on this together next week?

**Comment by hallahan** [comment]
Any traction on this? Should I close?

**Comment by jj0hns0n** [comment]
lets close for now. not necessary immediately

**Comment by hallahan** [comment]
Ok.
