### ISSUE TITLE
GitHub pages openmapkit.org site

### ISSUE THREAD

**Issue by jj0hns0n** [AmericanRedCross/OpenMapKitAndroid#23]
We need a site on openmapkit.org ... potentially using GitHub pages?

**Comment by jharpster** [comment]
We have the domain already. Just need someone to take that on.

**Comment by jj0hns0n** [comment]
I noticed it was register to you :)

**Comment by dalekunce** [comment]
@jharpster I'm going to assign an intern to this with a completion date of May 1st. Do you want to be involved in the setup and design?

**Comment by hallahan** [comment]
Bootstrap + Jekyll for maintainability

**Comment by jj0hns0n** [comment]
+1 on Bootstrap + jekyll

**Comment by hallahan** [comment]
I'm getting the basic Jekyll site on gh-pages setup to hand off to the intern. A good tutorial I'm referencing:

http://24ways.org/2013/get-started-with-github-pages/

**Comment by hallahan** [comment]
Note that gh-pages will have site oriented files and will not contain the source for the Android project. This branch should be checked out into a completely separate repo (aka OpenMapKit_website). gh-pages and master should never talk to each other.

**Comment by jj0hns0n** [comment]
I think you can just make a separate repo for openmapkit.github.com but you
may need the openmapkit team for that.

**Comment by hallahan** [comment]
Either can work fine. I've got an orphan gh-pages branch that seems fine. Some sorta Jekyll snafu. Just about ready to hand it off. I'm down with making an OpenMapKit org, but then how would we switch this repo to the org in a way that makes sense?

**Comment by jj0hns0n** [comment]
Yeah, @calimapnerd can we snag this GH org? https://github.com/openmapkit

**Comment by hallahan** [comment]
OK, well I have a starting point ready, however, it's setup for `http://openmapkit.org/`, so it's not going to show up correctly at http://americanredcross.github.io/OpenMapKit/

**Comment by hallahan** [comment]
We need to set the A record on the DNS server.

**Comment by hallahan** [comment]
OK, @jharpster setup the A records. Ready for the intern to start cooking!

http://openmapkit.org/

**Comment by dalekunce** [comment]
@hallahan what directory is hosting the site.

**Comment by hallahan** [comment]
It's on the gh-pages branch of this repo. Interestingly, I just learned that all of this is running on bare-metal servers on Rackspace infrastructure--not Amazon.

https://github.com/AmericanRedCross/OpenMapKit/tree/gh-pages

**Comment by dalekunce** [comment]
Moving this to its own milestone. The website is a whole milestone itself.

**Comment by hallahan** [comment]
This is now a whole repo in itself. See https://github.com/AmericanRedCross/OpenMapKitWebsite
