### ISSUE TITLE
Switch to MapBox GL

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/OpenMapKitAndroid#25]

**Comment by hallahan** [comment]
This will really bring the quality of the map component to the next level. A useful side project would be to extend the overpass api to serve straight vector tiles instead of xml. Also, it might be smart to add osm support to tippecanoe:  https://github.com/mapbox/tippecanoe

**Comment by hallahan** [comment]
Last night I pulled down the lastest MapboxGL Native and build it for Mac Cocoa with no issues whatsoever--very impressed. I will experiment with the Android build and evaluate the LOE and if it is appropriate to make the switch at this point in the project.

**Comment by hallahan** [comment]
For Android, offline MBTiles has not yet been implemented. We have to either implement this or wait for it to be completed for this to be a viable option.

**Comment by hallahan** [comment]
Current master does not build for Android:

https://github.com/mapbox/mapbox-gl-native/issues/1010

**Comment by hallahan** [comment]
I got MapboxGL Android running on the RedCross dev Galaxy S3 phone:

![mapboxgl-android](https://cloud.githubusercontent.com/assets/556367/6694344/ebb78600-cc96-11e4-91a6-ced5b8be703f.png)

This is several light years better than the Mapbox Android SDK. One major thing that needs to happen: we need MBTiles support so we can store vector tiles offline. It's on Mapbox's todo list but not a priority. 

The consensus is that this needs to be part of the native C++ library so all platforms can use it. There's tons of open implementations out there in Java, JavaScript, as well as some C++ that writes MBTiles in [tippecanoe](https://github.com/mapbox/tippecanoe). So, I consider this an obtainable goal.

**Comment by hallahan** [comment]
Even Esri is doing it. We need to hop on this bus before it leaves the station:

http://video.esri.com/watch/4215/smart-mapping-with-vector-map-tiles

https://www.mapbox.com/blog/vector-tile-adoption/

**Comment by dalekunce** [comment]
I agree lets see if we can get mapbox to prioritize this.

**Comment by dalekunce** [comment]
The [Amigo android](https://www.amigocloud.com/homepage/index) renderer looks a little more advanced than the mapbox GL one at the moment.

**Comment by hallahan** [comment]
Let's consider this not an option unless Mapbox implements:

https://github.com/mapbox/mapbox-gl-native/issues/584
https://github.com/mapbox/mapbox-gl-native/issues/352

Also, engineering a pipeline to make vector tiles in a way that makes sense for our application is a major undertaking. Would we want Mapnik to do this, or one of Mapbox's more hip, newer alternatives?

cc/ @mikelmaron

**Comment by mikelmaron** [comment]
@hallahan offline is a priority, making good progress here: https://github.com/mapbox/gl-internal/issues/322#issuecomment-159107307

**Comment by zugaldia** [comment]
Happy to report that that we're making good progress on offline and it's a current priority, you can follow the progress here: https://github.com/mapbox/mapbox-gl-native/issues/2939
