### ISSUE TITLE
Complete Standalone OpenMapKit Functionality

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/OpenMapKitAndroid#43]
We need to complete the functionality where OMK can edit tags when not working with ODK Collect.

**Comment by dalekunce** [comment]
This is low priority for me at the moment. All of the use cases use ODK.

**Comment by hallahan** [comment]
We'll figure this out as part of the provisioning feature.

**Comment by hallahan** [comment]
Now that a year or so has gone by, I'd like to close this issue. I think for OpenMapKit, it really should always go along with ODK Collect. Creating a stand-alone mobile OSM editor should be a stand-alone project. Perhaps some day we could create a POSM Android that does that.

Because standalone mode never really worked, we now always prompt the user to launch ODK Collect. If ODK Collect is not installed (we detect that now), we provide a prompt to download Collect in the Play Store.

See https://github.com/AmericanRedCross/OpenMapKitAndroid/issues/88

and

https://github.com/AmericanRedCross/OpenMapKitAndroid/commit/4f1bef86c025b5a7b9bd952ca1dba6298001624a
