### ISSUE TITLE
Implicit Tag Recorded without UI

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/OpenMapKitAndroid#57]
It would make sense to always add the tag 

```xml
<tag k="source" v="OpenMapKit"/>
```

**Comment by dalekunce** [comment]
yeah great idea.

**Comment by vdeparday** [comment]
Could we also add project name and add it automatically as a tag to the
changeset comment and in the source tag? Not sure where it would be
inputed? I suppose by the admin who is setting up the form?

**Comment by dalekunce** [comment]
Keeping with our hashtag model for tracking edits it would be cool to pre-populate them via xlsform if we are able to submit directly from the phone.

**Comment by hallahan** [comment]
What was the verdict with this one? Are we going to do this in the `source` tag. The answer was no with `created_by`.

**Comment by hallahan** [comment]
I think rather than hitting this issue head on, we instead want to have a constraint

__Implicit Tag Recorded without UI__

That way, you could specify in your XLS Form the a specific key / value, such as k="source" v="OpenMapKit", or whatever. This leaves things open to unforeseen use cases.

**Comment by hallahan** [comment]
A good example of an implicit tag would be `source=survey`. We'd want this to be added pretty much always, based on our current workflow.

Can you think of any other tags that might be implicit?

cc/ @dalekunce @PaulUithol

**Comment by hallahan** [comment]
For a specific survey, implicit `addr:city` and `addr:state` might make sense.

**Comment by PaulUithol** [comment]
In our case, we had separate forms for each amenity we were surveying. So
`amenity=bank `, `amenity=atm` etc would've been implicit. Some `addr` tags
are a good one as well indeed.

**Comment by hallahan** [comment]
Done.
