### ISSUE TITLE
values can exist but be hidden from the user in the survey

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/OpenMapKitAndroid#67]
A building can have a value associated with a key. And it will display in the initial screen on selection. But if it is not an option in the survey, when in the survey it's existence will be hidden from the user and it will appear as if the building has no associated value. The user may then inadvertently overwrite a more detailed value with one of the values that are options in the survey.

In the below example the building is just building=yes. But if it were tagged building=apartments and then the user surveyed it as building=residential, the level of detail in OSM would be reduced. This kind of thing affects tags that fall into the "all squares are rectangles but not all rectangles are squares" issue. All building=house are building=residential but not all residential are house. A survey may not have all the possible preexisting (and potentially more specific) values.

![0001](https://cloud.githubusercontent.com/assets/4806884/7965792/d08354d8-09ed-11e5-9939-dab0d0972a6f.png)

![0002](https://cloud.githubusercontent.com/assets/4806884/7965795/d41e2c4e-09ed-11e5-9446-473f47784505.png)

**Comment by hallahan** [comment]
In this instance, I think we want to check and see if a value exists that's not in the choices and then add it as a choice.

**Comment by hallahan** [comment]
This has been solved with the custom multiple choice input widget implemented for HOT. #105
