### ISSUE TITLE
proximity_settings.xml in app assets and off by default

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/OpenMapKitAndroid#75]
We do not want the proximity feature to be on by default, because most of the time we don't want to disable users like this.

We have no example `proximity_settings.xml` file to work with as an example. We should have an example one by default, and this should be in the app assets. If you have a settings file in the device storage, this will override the default settings file.

cc/ @mberg @imwongela

**Comment by mberg** [comment]
Nick,

We have a proximity settings file. I'll have Isaac send it over.  We were
working on a pr but needed to do some refactoring first.  This will need to
optional as some users won't want to have their gps turned on all the time
I'm sure.

Matt

**Comment by imwongela** [comment]
@hallahan
Will disable this to be off by default. However we'd like it to be easy for user to copy or edit the file easily and not sure if this is possible in the app assets.

**Comment by hallahan** [comment]
The idea is to have a settings file in the app assets as the default fall back. 

We want to look in the right spot in external storage for the settings file. If that fails to load (throws an exception), we want to catch that exception by loading a default settings file in the app assets.

**Comment by hallahan** [comment]
This was taken out, we don't want to require anything extra like settings files when downloading from Play Store.
