### ISSUE TITLE
Proximity functionality should not be in Mapbox

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/OpenMapKitAndroid#76]
I've applied the latest Mapbox Android SDK updates to the branch [mapbox_update](https://github.com/AmericanRedCross/OpenMapKit/tree/mapbox_update), however, this cancels out a lot of the Proximity Functionality in #70.

I do not think this proximity work is appropriate for pulling into Mapbox's code base, and it is very specific to OpenMapKit. I'm thinking we will need to take this functionality back out from master. We need to put this work probably in its own module with OpenMapKit, not the Mapbox Android SDK.

I briefly attempted to do this when merging the pull request, and I am aware that it isn't trivial, but it shouldn't be too bad. Always keep in mind that the SDK is subject to update and is a general library many different projects use. Though I have it hard coded in the project, I still bring in updates from Mapbox's repo.

I'm going to go forward with the POI work #11 without proximity since I need the latest revision of the SDK for improved marker functionality. Nonetheless, let's figure this out.

cc/ @mberg @imwongela

**Comment by imwongela** [comment]
@hallahan 
I will try to get the proximity functionality separated from the Mapbox SDK to make updates to the SDK easier. Thanks.

**Comment by hallahan** [comment]
No longer in code.
