### ISSUE TITLE
Opening OpenMapKit Pushes User to ODK Collect

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/OpenMapKitAndroid#88]
One thing that confuses new users is that they try and open OpenMapKit directly rather than go in via ODK Collect. 

One idea that could solve this confusion is to check to see if OpenMapKit was initiated by ODK Collect. If it was not, it will just launch the user INTO ODK Collect.

This shouldn't be hard to do.

**Comment by felixholl** [comment]
If ODK is not running, OMK crashed when you push the 'save to odk' button.
I'm sure this would happen in the field a lot and confuse the user.

**Comment by hallahan** [comment]
:+1: Agreed.

**Comment by dalekunce** [comment]
@hallahan didn't we put this feature in. Can we close this issue?

**Comment by hallahan** [comment]
Not yet, still needs to happen.
