### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by mberg** [AmericanRedCross/OpenMapKitAndroid#90]
Nick - you are cranking away which is awesome.  Since you are using version numbers could we keep a short changelog somewhere.  Ie) It would be super helpful to know the difference between v.011 and 0.12

**Comment by dalekunce** [comment]
Agreed, on the changelog. @mberg from this point forward we are moving to a release model. So we will document all issues into incremental versions. @hallahan @jharpster

**Comment by hallahan** [comment]
This should be part of a build process. Maybe with CI too. Thoughts, @jj0hns0n ?

**Comment by hallahan** [comment]
How about we use Github's release functionality for changelogs? More automatic that way.

https://github.com/AmericanRedCross/OpenMapKitAndroid/releases

https://github.com/AmericanRedCross/OpenMapKitAndroid/releases/new

See #107 as well. If everyone is ok with this method, let's do the next release this way and close these issues?

**Comment by hallahan** [comment]
We have a log of changes in the latest GitHub release:

https://github.com/AmericanRedCross/OpenMapKitAndroid/releases/tag/v0.14
