### ISSUE TITLE
osm file of new POIs not opening

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/OpenMapKitAndroid#96]
created a simple survey with only an OMK question and only one tag
<img width="375" alt="screen shot 2015-11-15 at 4 54 01 pm" src="https://cloud.githubusercontent.com/assets/4806884/11168447/821f468c-8bb9-11e5-9864-a332afe5fedf.png">
uploaded some completed forms
<img width="616" alt="screen shot 2015-11-15 at 4 55 29 pm" src="https://cloud.githubusercontent.com/assets/4806884/11168453/bd01501a-8bb9-11e5-9b29-7d4fc127ae1f.png">
and then tried to open the downloaded .osm file in JOSM but got the following error
<img width="573" alt="screen shot 2015-11-15 at 4 52 48 pm" src="https://cloud.githubusercontent.com/assets/4806884/11168454/d037e0b8-8bb9-11e5-9c70-bdec8bcbb23c.png">

**Comment by hallahan** [comment]
This is another Ona specific issue.

https://github.com/onaio/onadata

Could you please provide the OSM XML file shown here?

**Comment by danbjoseph** [comment]
ah... the file is empty/ Zero bytes. a very premature end indeed.

**Comment by mberg** [comment]
@danbjoseph what server did you get this error?  Can you file this as a ticket on the onadata repo? This should be working but want to double check what's going on.

**Comment by danbjoseph** [comment]
it's from the Red Cross instance

**Comment by dalekunce** [comment]
@mberg when these changes are pushed to master we can bring them into the Red Cross system. Can you provide an update/install walkthrough.

**Comment by mberg** [comment]
@dalekunce - yes will do.  Once this is ready - we'll touch base to try and
come up with a good strategy for keeping the Red Cross version up to date.

**Comment by hallahan** [comment]
Closing, Ona specific issue.
